-- 제귀함수로 세대 새는 함수 만들기
WITH RECURSIVE CTE AS (
# 최초 대장균 개체 찾기
SELECT ID, PARENT_ID, 1 AS CNT
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
# 부모 있는 개체 찾기
SELECT C.ID, C.PARENT_ID, CTE.CNT + 1
FROM ECOLI_DATA C JOIN CTE ON C.PARENT_ID = CTE.ID)

SELECT ID
FROM CTE
WHERE CNT = 3
ORDER BY 1;