SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE NAME LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
ORDER BY 2;



# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS 
# WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'DOG'
# ORDER BY 2;