-- 더 이상 업그레이드 할 수 없다 == PARENT_ITEM_ID에 없다.
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                            FROM ITEM_TREE
                            WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY 1 DESC;
