-- 더 이상 업그레이드 할 수 없다. = 마지막 ratent_item_id에 내가 없다.
-- II.ITEM_ID는 PARENT가 된다, IT.ITEM_ID는 CHILD가 된다.
SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY 1 DESC;