-- 왜 BETWEEN으로 하면 안될까?
# SELECT ID, 
#     CASE 
#         WHEN A.PER BETWEEN 0 AND 0.25 THEN 'CRITICAL'
#         WHEN A.PER BETWEEN 0.26 AND 0.5 THEN 'HIGH'
#         WHEN A.PER BETWEEN 0.51 AND 0.75 THEN 'MEDIUM'
#         WHEN A.PER BETWEEN 0.76 AND 1 THEN 'LOW'
#     END AS COLONY_NAME
# FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
#      FROM ECOLI_DATA ) A
# ORDER BY ID;

SELECT ID, 
    CASE 
        WHEN A.PER<= 0.25 THEN 'CRITICAL'
        WHEN A.PER<= 0.5 THEN 'HIGH'
        WHEN A.PER<=0.75 THEN 'MEDIUM'
        WHEN A.PER<= 1 THEN 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
     FROM ECOLI_DATA ) A
ORDER BY ID;