SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND (SEX_UPON_OUTCOME LIKE "Neutered%" OR SEX_UPON_OUTCOME LIKE 'Spayed%');