-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, S.SCORE AS SCORE
FROM REST_INFO RI JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
                        FROM REST_REVIEW 
                        GROUP BY REST_ID) S USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;

-- REST_INFO 체크
# SELECT *
# FROM REST_INFO 
# WHERE ADDRESS LIKE '서울%'

-- 식당 평균점수 구하기
# SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
# FROM REST_REVIEW 
# GROUP BY REST_ID