-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM ONLINE_SALE OS JOIN USER_INFO UI USING (USER_ID)
WHERE UI.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3

--