SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS 
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY 1;


# SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS count
# FROM ANIMAL_INS 
# WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
# GROUP BY ANIMAL_TYPE
# ORDER BY 1;


# -- 일단 확인
# SELECT *
# FROM ANIMAL_INS;