-- 2021년에 가입한 회원 출력
WITH J AS(
SELECT *
FROM USER_INFO 
WHERE JOINED LIKE '2021%'
),
-- 21년 가입 회원 중 상품 구매한 회원 수
PAID AS (
SELECT *
FROM ONLINE_SALE OS JOIN USER_INFO UI USING(USER_ID)
WHERE JOINED LIKE '2021%'
)

-- 적용해서 
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT PAID.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT PAID.USER_ID)/ COUNT(DISTINCT J.USER_ID),1) AS PUCHASED_RATIO
FROM J, PAID
GROUP BY 1,2




# WITH JU AS (
# -- 2021년에 가입한 회원 출력; 158명
# SELECT USER_ID
# FROM USER_INFO 
# WHERE JOINED LIKE "2021%"),

# SU AS (
# -- 21년에 가입한 회원 중 구매한 회원 출력; 83
# SELECT *
# FROM ONLINE_SALE OS JOIN USER_INFO USING(USER_ID)
# WHERE YEAR(JOINED) = 2021)

# -- 정답
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT SU.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT SU.USER_ID)/COUNT(DISTINCT JU.USER_ID), 1) AS PUCHASED_RATIO
# FROM SU, JU
# GROUP BY 1, 2