-- 반복 함수 사용해서 진행
WITH RECURSIVE CTE AS 
(
SELECT ID , PARENT_ID , 1 AS CNT  -- 최초 대장균은 1
FROM ECOLI_DATA 
WHERE PARENT_ID IS NULL
    
UNION ALL
    
SELECT A.ID , A.PARENT_ID, C.CNT +1 
FROM ECOLI_DATA A JOIN CTE C ON A.PARENT_ID = C.ID
)

-- 자식이 없는 것
SELECT COUNT(*) AS COUNT, CNT AS GENERATION
FROM CTE 
# 부모id에 없어야 한다. = 자식이 없다.
WHERE ID NOT IN (SELECT PARENT_ID FROM CTE WHERE PARENT_ID IS NOT NULL)
GROUP BY 2
ORDER BY 2;

-- 이해하려고 일단 조인
# SELECT A.ID, A.PARENT_ID, B.ID, B.PARENT_ID
# FROM ECOLI_DATA A LEFT JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID;
-- B.ID 가 A.ID 에 없어야 한다.