SELECT DISTINCT CAR_ID,
       CASE 
           WHEN EXISTS (
               SELECT 1 
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
               WHERE H.CAR_ID = R.CAR_ID 
                 AND '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE
           ) 
           THEN '대여중'
           ELSE '대여 가능'
       END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
ORDER BY CAR_ID DESC;

















# -- 16일 대여
# -- START_DATE< 16일 AND END_DATE >=16일 이면 대여 중
# -- END_DATE가 16일 전 이거나, START_DATE가 16일 이후면 대여 가능
# SELECT CAR_ID, CASE WHEN SUM(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
# ELSE 0 END) = 1 THEN '대여중' ELSE '대여 가능' 
# END AS AVAILABILITY 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY 1
# ORDER BY 1 DESC;