# SELECT AI.NAME, AI.DATETIME
# FROM ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO USING(ANIMAL_ID)
# WHERE AI.ANIMAL_ID IS NOT NULL AND AO.ANIMAL_ID IS NULL
# ORDER BY 2 LIMIT 3;

-- 달리 풀어보기
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
WHERE AI.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                          FROM ANIMAL_OUTS)
ORDER BY 2 LIMIT 3;