-- 코드를 입력하세요
SELECT A.PRODUCT_ID, PRODUCT_NAME, (A.PRICE*B.SALES) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS SALES
                        FROM FOOD_ORDER
                        WHERE PRODUCE_DATE LIKE "2022-05%"
                        GROUP BY PRODUCT_ID) B USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;

-- 22년 5월 생산된 PRODUCT_ID별 주문량
# SELECT PRODUCT_ID, SUM(AMOUNT)
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE LIKE "2022-05%"
# GROUP BY PRODUCT_ID;