-- 트럭인 duration에 따른 DURATION_TYPE 출력
WITH DURATION AS (
SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE)+1) AS DURATION, 
    CASE WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 90 THEN '90일 이상'
         WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 30 THEN '30일 이상'
         WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 7 THEN '7일 이상'
         ELSE NULL END AS DURATION_TYPE , DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR CC USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
),
-- 트럭의 DURATION_TYPE만 가지고 오기
TRUCK_DURATION_TYPE AS (
SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE CAR_TYPE = '트럭'
)

-- 합치기 ; 자꾸 틀렸다고 뜨는데 GROUP BY HISTORY_ID를 해야 할 것 같음
SELECT A.HISTORY_ID, ROUND(DAILY_FEE*DURATION*(1-IFNULL(DISCOUNT_RATE,0)*0.01)) AS FEE
FROM DURATION A
    LEFT JOIN TRUCK_DURATION_TYPE C ON (A.DURATION_TYPE = C.DURATION_TYPE)
ORDER BY 2 DESC, 1 DESC;

-- HISTORY 확인 : 34건
-- 34건에 대한 금액 산정이 되어야 한다.
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR CC USING(CAR_ID)
# WHERE CAR_TYPE = '트럭';


# # 722 나는 3162000 정답은 29~
# -- DAILY 102,000  기간 31 할인 8퍼 0.92
# -- 근데 왜 722만 이렇게 나오지? 이거 왜 널로 된거지?
# SELECT A.HISTORY_ID, ROUND(DAILY_FEE*DURATION*(1-IFNULL(DISCOUNT_RATE,0)*0.01)) AS FEE, A.DURATION, A.DURATION_TYPE, C.DURATION_TYPE, DISCOUNT_RATE
# FROM DURATION A
#     LEFT JOIN TRUCK_DURATION_TYPE C ON (A.DURATION_TYPE = C.DURATION_TYPE)
# WHERE A.HISTORY_ID=722;

