-- 트럭인 duration에 따른 DURATION_TYPE 출력
# WITH DURATION AS (
# SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE)+1) AS DURATION, 
#     CASE WHEN DATEDIFF(END_DATE+1, START_DATE) >= 90 THEN '90일 이상'
#          WHEN DATEDIFF(END_DATE+1, START_DATE) >= 30 THEN '30일 이상'
#          WHEN DATEDIFF(END_DATE+1, START_DATE) >= 7 THEN '7일 이상'
#          ELSE NULL END AS DURATION_TYPE , DAILY_FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR CC USING(CAR_ID)
# WHERE CAR_TYPE = '트럭'
# ),
# -- 트럭의 DURATION_TYPE만 가지고 오기
# TRUCK_DURATION_TYPE AS (
# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
# WHERE CAR_TYPE = '트럭'
# )

-- 합치기 ; 자꾸 틀렸다고 뜨는데 GROUP BY HISTORY_ID를 해야 할 것 같음
# SELECT A.HISTORY_ID, ROUND(DAILY_FEE*DURATION*(1-IFNULL(DISCOUNT_RATE,0)*0.01)) AS FEE
# FROM DURATION A
#     LEFT JOIN TRUCK_DURATION_TYPE C ON (A.DURATION_TYPE = C.DURATION_TYPE)
# ORDER BY 2 DESC, 1 DESC;

-- GROUP BY 사용
# SELECT A.HISTORY_ID, ROUND(DAILY_FEE*DURATION*(1-IFNULL(DISCOUNT_RATE,0)*0.01)) AS FEE
# FROM DURATION A
#     LEFT JOIN TRUCK_DURATION_TYPE C ON (A.DURATION_TYPE = C.DURATION_TYPE)
# GROUP BY 1
# ORDER BY 2 DESC, 1 DESC;

-- HISTORY 확인 : 34건
-- 34건에 대한 금액 산정이 되어야 한다.
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR CC USING(CAR_ID)
# WHERE CAR_TYPE = '트럭';

# 724
# DAILY_FEE : 168000
# 기간은 41
# 할인은 8%
# 계산 : 6,336,960

WITH CJ AS (
SELECT  RH.HISTORY_ID
        ,C.CAR_TYPE
        ,C.DAILY_FEE
        ,DATEDIFF(RH.END_DATE,RH.START_DATE)+1 AS DAYS
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
  JOIN  CAR_RENTAL_COMPANY_CAR AS C
    ON  RH.CAR_ID = C.CAR_ID
 WHERE  C.CAR_TYPE = '트럭'
)
, CAR_RENTAL AS (
SELECT  CJ.*
        ,CASE 
        WHEN DAYS >= 90 THEN 15
        WHEN DAYS >= 30 THEN 8
        WHEN DAYS >= 7 THEN 5
        ELSE 0 END RATE
  FROM  CJ
  JOIN  CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON  CJ.CAR_TYPE = DP.CAR_TYPE
 GROUP
    BY  CJ.HISTORY_ID
)

SELECT  HISTORY_ID
        ,ROUND(DAILY_FEE * DAYS * (1-RATE*0.01),0) AS FEE
  FROM  CAR_RENTAL
 ORDER
    BY  FEE DESC, HISTORY_ID DESC