-- JULY 총 주문량 상위 3개
# SELECT FLAVOR, SUM(TOTAL_ORDER) AS AMOUNT
# FROM JULY
# GROUP BY FLAVOR

-- FIRST_HALF 랑 합치기
SELECT FLAVOR
FROM FIRST_HALF A JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS AMOUNT
                        FROM JULY
                        GROUP BY FLAVOR) B USING (FLAVOR)
ORDER BY (A.TOTAL_ORDER+B.AMOUNT) DESC LIMIT 3;
