-- 정답
SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A LEFT JOIN PATIENT P USING(PT_NO) LEFT JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY 6;

# SELECT *
# FROM APPOINTMENT
# ORDER BY 1;













-- 정답
# SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
# FROM APPOINTMENT A 
# LEFT JOIN PATIENT P USING (PT_NO) 
# LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
# WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N'  AND A.MCDP_CD = 'CS' 
# ORDER BY APNT_YMD;


# -- 2022년 4월 13일 취소되지 않은 CS 예약건
# SELECT APNT_NO, APNT_YMD, MCDP_CD
# FROM APPOINTMENT 
# WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'