-- HOUR 함수 사용해서 그룹별 카운트 하기
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
ORDER BY 1;

-- 0~24 까지 나오게 하기
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR_NUM
    UNION ALL
    SELECT HOUR_NUM+1
    FROM CTE
    WHERE HOUR_NUM <23)
    
SELECT HOUR_NUM AS HOUR, IFNULL(COUNT, 0) AS COUNT
FROM CTE LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
ORDER BY 1) A ON (CTE.HOUR_NUM = A.HOUR)
ORDER BY HOUR;

