-- 거래상태가 완료인 70만원 이상인
# SELECT WRITER_ID, PRICE
# FROM USED_GOODS_BOARD 
# WHERE STATUS = 'DONE' AND PRICE>=700000;

-- 정답
SELECT USER_ID, NICKNAME, SUM(PRICE)
FROM USED_GOODS_USER UGU JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE)>=700000
ORDER BY 3;