-- 1등 리뷰 수 및 ID 체크
# SELECT MEMBER_ID
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1;

-- 리뷰 테이블에 회원 테이블을 ID로 묶어서 이름 내용 출력
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS V
FROM REST_REVIEW JOIN MEMBER_PROFILE USING (MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1)
ORDER BY 3, 2;

-- REST_REVIEW 테이블 확인, 리뷰수가 같을 때는 어떻게 되는 걸까?
# SELECT MEMBER_ID, MEMBER_NAME, COUNT(REVIEW_ID)
# FROM REST_REVIEW JOIN MEMBER_PROFILE USING (MEMBER_ID)
# GROUP BY MEMBER_ID, MEMBER_NAME
# ORDER BY 3 DESC;