SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II LEFT JOIN ITEM_TREE IT USING(ITEM_ID)
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
                        FROM ITEM_INFO 
                        WHERE RARITY = 'RARE')
ORDER BY 1 DESC;