-- 코드를 작성해주세요
SELECT B.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B USING(ITEM_ID)
WHERE B.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = "RARE")
ORDER BY ITEM_ID DESC;