-- 형질 출력
# SELECT GENOTYPE	
# FROM ECOLI_DATA 

-- 정답
SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID
WHERE C.PARENT_ID IS NOT NULL AND
P.GENOTYPE = C.GENOTYPE & P.GENOTYPE
ORDER BY 1;