-- 8월~10월 기간의 내역 뽑기 + 해당 기간 동안 5회 이상
SELECT CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 1
HAVING COUNT(CAR_ID) >= 5
ORDER BY 1 DESC;

-- 그러한 아이디인 자동차 8, 9, 10월  사용 회수 보기
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                GROUP BY 1
                HAVING COUNT(CAR_ID) >= 5) B USING(CAR_ID)
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 1, 2
ORDER BY 1, 2 DESC;








-- 이해가 안 됨, 해당 아이디의 8~10월까지만 세어야 해서, 조건 안 넣으면 전체 기간 카운팅
# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND CAR_ID IN (SELECT CAR_ID
#                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                  WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
#                  GROUP BY CAR_ID
#                  HAVING COUNT(*) >=5)
# GROUP BY MONTH, CAR_ID
# ORDER BY 1, 2 DESC;