-- 연도별 가장 큰 대장균의 크기 출력
# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
# FROM ECOLI_DATA 
# GROUP BY 1

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE-SIZE_OF_COLONY AS YEAR_DEV, ID
FROM (SELECT *, YEAR(DIFFERENTIATION_DATE) AS YEAR
      FROM ECOLI_DATA ) ED JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA 
GROUP BY 1) EED USING(YEAR)
ORDER BY 1, 2;