-- 연도별 가장 큰 크기 구하기
WITH MAX_SIZE AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA 
GROUP BY 1
ORDER BY 1, 2
),
-- 연도 출력
YEAR_DATA AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID
FROM ECOLI_DATA
)


-- 정답
SELECT YD.YEAR, (MAX_SIZE-SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM YEAR_DATA YD JOIN MAX_SIZE USING(YEAR)
ORDER BY 1, 2;