# SELECT FISH_TYPE, MAX(LENGTH)
# FROM FISH_INFO 
# GROUP BY FISH_TYPE

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                            FROM FISH_INFO 
                            GROUP BY FISH_TYPE)
ORDER BY 1;