-- 종류별 가장 큰 길이
# SELECT FISH_TYPE, MAX(LENGTH)
# FROM FISH_INFO
# GROUP BY FISH_TYPE;

-- 정답
SELECT ID, FISH_NAME, FI.LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI USING(FISH_TYPE)
WHERE (FI.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                                FROM FISH_INFO
                                GROUP BY FISH_TYPE)
ORDER BY 1;