SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO B USING(FISH_TYPE)
WHERE (A.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(IFNULL(LENGTH, 10))
                                FROM FISH_INFO
                                GROUP BY FISH_TYPE)
ORDER BY ID;

