-- SCORE 합 EMP_NO 출력
# SELECT EMP_NO, SUM(SCORE) AS SCORE
# FROM HR_GRADE 
# WHERE YEAR = 2022
# GROUP BY EMP_NO

-- 정답
SELECT HG.SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
                            FROM HR_GRADE 
                            WHERE YEAR = 2022
                            GROUP BY EMP_NO) HG USING(EMP_NO)
ORDER BY 1 DESC LIMIT 1;
