-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, B.EMP_NO AS EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS A JOIN HR_GRADE AS B USING (EMP_NO)
WHERE YEAR = 2022
GROUP BY B.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1;