-- 코드를 입력하세요
SELECT A.TITLE AS TITLE, A.BOARD_ID AS BOARD_ID, B.REPLY_ID AS REPLY_ID, B.WRITER_ID AS WRITER_ID, B.CONTENTS AS CONTENTS, DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE, TITLE;