-- 조회수 게시물 BOARD_ID 출력
WITH B AS(
SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC LIMIT 1
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/',FILE_ID,FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE 
WHERE BOARD_ID IN (SELECT *
                    FROM B)
ORDER BY 1 DESC;

