-- GROUP BY에 없는 컬럼 SELECT에 쓰면 매칭되어 나오지 않는다.
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT 
# WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE)
#                         FROM FOOD_PRODUCT
#                         GROUP BY CATEGORY
#                         HAVING CATEGORY IN ( '과자', '국', '김치', '식용유'))
# ORDER BY PRICE DESC;

-- WINDOW 함수 사용
SELECT A.CATEGORY, A.MAX_PRICE, A.PRODUCT_NAME
FROM (SELECT CATEGORY, PRICE,
      MAX(PRICE) OVER (PARTITION BY CATEGORY) MAX_PRICE, PRODUCT_NAME
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) A
WHERE A.MAX_PRICE = A.PRICE
ORDER BY 2 DESC;