-- NULL은 10으로 바꿔서 평균길이 33인 물고기 종류별 잡은 수, 최대 길이, 물고기 종류
SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH , FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10))>=33
ORDER BY 3;