-- FROND END 코드 출력
WITH FE AS (
SELECT SUM(CODE) AS CODE
FROM SKILLCODES 
WHERE CATEGORY = 'Front End'
),

-- 파이썬 코드 출력
PY AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'Python'
),

-- C# 스킬 코드 출력
C AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#'
),

-- GRADE 만들기
GRADEV AS (
SELECT CASE WHEN (SKILL_CODE & FE.CODE) AND (SKILL_CODE & PY.CODE) THEN 'A'
            WHEN SKILL_CODE & C.CODE THEN 'B'
            WHEN SKILL_CODE & FE.CODE THEN 'C'
            END AS GRADE, ID, EMAIL
FROM DEVELOPERS, FE, PY, C
)

SELECT *
FROM GRADEV
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;