-- 코드를 입력하세요
SELECT CASE WHEN F=0 THEN 0
            WHEN F>=1 THEN F*10000
        END AS PRICE_GROUP,
        COUNT(*) AS PRODUCTS
FROM (SELECT FLOOR(PRICE/10000) AS F 
      FROM PRODUCT) A
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;